const TYPES = {
    SELECTED_PERSON: 'SELECTED_PERSON',
    NONE_SELECTED: 'NONE_SELECTED',
    FORM_UPDATE: 'FORM_UPDATE',
    NEW_CONTACT: 'NEW_CONTACT',
    ADD_PERSON: 'ADD_PERSON',
    INITIAL_FETCH: 'INITIAL_FETCH'
}

export default TYPES