const TYPES = {
    SELECTED_PERSON: 'SELECTED_PERSON',
    NONE_SELECTED: 'NONE_SELECTED',
    FORM_UPDATE: 'FORM_UPDATE',
    NEW_CONTACT: 'NEW_CONTACT',
    ADD_PERSON: 'ADD_PERSON',
    INITIAL_FETCH: 'INITIAL_FETCH',
    DELETE_CONTACT: 'DELETE_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    SAVE_CONTACT: 'SAVE_CONTACT',
}

export default TYPES